import "./globals.css";

// import MainFooter from "./components/MainFooter";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tourism",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      {/* <MainFooter /> */}
    </html>
  );
}
